[
    'acorn squash',
    'alfalfa sprouts',
    'anchovies',
    'apple',
    'apples',
    'artichoke',
    'arugula',
    'asparagus',
    'aubergine',
    'avocado',
    'bacon',
    'baking powder',
    'baking soda',
    'baking sugar',
    'bar sugar',
    'basil',
    'beans',
    'bell peppers',
    'blackberries',
    'bok choy',
    'brassicas',
    'bread',
    'breadfruit',
    'broad beans',
    'broccoflower',
    'broccoli',
    'broccoli rabe',
    'broccolini',
    'brown sugar',
    'brussels sprouts',
    'butter',
    'butternut pumpkin',
    'butternut squash',
    'cabbage',
    'cactus, edible',
    'calabrese',
    'cane sugar',
    'cannabis',
    'capsicum',
    'caraway',
    'carrot',
    'caster sugar',
    'castor sugar',
    'catfish (farm-raised)',
    'cauliflower',
    'cayenne pepper',
    'celeriac',
    'celery',
    'cereal grains',
    'chard',
    'cheese',
    'chicory',
    'chilli peppers',
    'chinese leaves',
    'chives',
    'chocolate',
    'cilantro',
    'cinnamon',
    'clarified butter',
    'coconut',
    'coconut milk',
    'cod',
    'coffee',
    'collard greens',
    "confectioners' sugar",
    'coriander',
    'corn',
    'corn syrup',
    'cottonseed oil',
    'courgette',
    'cream of tartar',
    'cucumber',
    'cumin',
    'daikon',
    'dairy products and dairy substitutes',
    'dandelion',
    'demerara sugar',
    'dough',
    'edible cactus',
    'eggplant',
    'eggs',
    'endive',
    'fats',
    'fava beans',
    'fiddlehead',
    'fiddlehead fern',
    'fish',
    'five spice powder',
    'flour',
    'frisee',
    'fructose',
    'fruit',
    'fruit sugar',
    'ful',
    'garam masala',
    'garlic',
    'gem squash',
    'ghee',
    'giblets',
    'ginger',
    'grains',
    'granulated sugar',
    'grape seed oil',
    'green onion',
    'heart of palm',
    'hemp',
    'herbs',
    'honey',
    'horse',
    'icing sugar',
    'isomalt',
    'jackfruit',
    'jaggery',
    'jams',
    'jellies',
    'jerusalem artichoke',
    'jicama',
    'kale',
    'kohlrabi',
    'kumara',
    'leavening agents',
    'leek',
    'legumes',
    'lemongrass',
    'lentils',
    'lettuce',
    'liver',
    'maize',
    'maple syrup',
    'meat',
    'milk',
    'mortadella',
    'mushroom',
    'mussels',
    'nanaimo bar mix',
    'nori',
    'nutmeg',
    'nutritional yeast flakes',
    'nuts',
    'octopuses',
    'oils',
    'okra',
    'olive',
    'olive oil',
    'onion',
    'orange blossom water',
    'oranges',
    'oregano',
    'oysters',
    'panch puran',
    'paprika',
    'parsley',
    'parsnip',
    'pear',
    'peas',
    'pepper',
    'peppers',
    'pineapple',
    'plantain',
    'poppy seeds',
    'potato',
    'potatoes',
    'poultry',
    'powdered sugar',
    'pumpkin',
    'pumpkin seeds',
    'radish',
    'rape',
    'raw sugar',
    'refined sugar',
    'rice',
    'rice flour',
    'rock sugar',
    'rum',
    'salmon',
    'salt',
    'salt cod',
    'scallion',
    'seafood',
    'seeds',
    'sesame seeds',
    'shallot',
    'skate',
    'soda',
    'soda, baking',
    'soybean',
    'spaghetti squash',
    'spek',
    'spices',
    'spinach',
    'spring onion',
    'squash',
    'stockfish',
    'sugar',
    'sunchoke',
    'sunflower seeds',
    'superfine sugar',
    'sweet potato',
    'sweetcorn',
    'sweeteners',
    'tahini',
    'taro',
    'teff',
    'tomato',
    'trout',
    'tubers',
    'tuna',
    'turbanado sugar',
    'turnip',
    'unrefined sugar',
    'vanilla',
    'vegetables',
    'watercress',
    'watermelon',
    'white mushroom',
    'white sugar',
    'xanthan gum',
    'yam',
    'yeast',
    'zucchini'
]